export const PATHS = {
  home: "/",
  about: "/about",
  spots: "/spots",
  spotDetail: "/spots/:spotId",
  seasons: "/seasons",
  seasonDetail: "/seasons/:seasonId",
  routes: "/routes",
  routeDetail: "/routes/:routeId",
  experiences: "/experiences",
  experienceDetail: "/experiences/:experienceId",
  map: "/map",
  recommend: "/recommend",
  booking: "/booking",
  bookingSuccess: "/booking/success",
  ar: "/ar",
  news: "/news",
  newsDetail: "/news/:newsId",
  faq: "/faq",
  contact: "/contact",
  login: "/login",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  soundFlower: "/sound-flower", 
  story: "/story",
} as const;